//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReturneeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndiVidual_Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndiVidual_Address()
        {
            this.Individuals = new HashSet<Individual>();
        }
    
        public System.Guid AddressID { get; set; }
        public System.Guid IndividualID { get; set; }
        public string Type { get; set; }
        public string AddressType { get; set; }
        public string BarangayName { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string BldgNo { get; set; }
        public string BldgName { get; set; }
        public string UnitNo { get; set; }
        public string Street { get; set; }
        public string Subdivision { get; set; }
        public string Pin { get; set; }
        public string text { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeogCol1 { get; set; }
        public string GeogCol2 { get; set; }
    
        public virtual Individual Individual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Individual> Individuals { get; set; }
    }
}
