//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReturneeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Individual()
        {
            this.IndiVidual_Address = new HashSet<IndiVidual_Address>();
            this.Individual_Travel = new HashSet<Individual_Travel>();
        }
    
        public System.Guid IndividualID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public string CivilStatus { get; set; }
        public string Occupation { get; set; }
        public string Religion { get; set; }
        public string TelepnoeNo { get; set; }
        public string MobileNo { get; set; }
        public string FullName { get; set; }

        public Nullable<System.Guid> AddressID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndiVidual_Address> IndiVidual_Address { get; set; }
        public virtual IndiVidual_Address IndiVidual_Address1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Individual_Travel> Individual_Travel { get; set; }
    }
}
