//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReturneeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Individual_Travel
    {
        public System.Guid ObjID { get; set; }
        public string TravelType { get; set; }
        public System.Guid TravelID { get; set; }
        public System.Guid IndividualID { get; set; }
    
        public virtual Individual Individual { get; set; }
        public virtual TravelList TravelList { get; set; }
    }
}
