//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReturneeManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReturneeManagement_DBEntities : DbContext
    {
        public ReturneeManagement_DBEntities()
            : base("name=ReturneeManagement_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Individual> Individuals { get; set; }
        public virtual DbSet<IndiVidual_Address> IndiVidual_Address { get; set; }
        public virtual DbSet<Individual_Travel> Individual_Travel { get; set; }
        public virtual DbSet<TravelList> TravelLists { get; set; }
    }
}
