//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReturneeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelList()
        {
            this.Individual_Travel = new HashSet<Individual_Travel>();
        }
    
        public System.Guid TravelID { get; set; }
        public string FlightVessel { get; set; }
        public string FlightCode { get; set; }
        public System.DateTime ArrivalDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Individual_Travel> Individual_Travel { get; set; }
    }
}
